Postgres database setup with pgadmin running on Docker
tgoprince/odh-alpinebits-destination-data-server pull request #29
Opened 2021-10-11 16:41 UTC by joaogoncalves777

Added support for a postgresql database together with pgadmin for development and testing. Each running on a separate docker container.

Docker images used were:
postgres (setupdb)
dpage/pgadmin4 (pgadmin)

- To run the db:

npm run setupdb (Default port 5432)

- After the db is set, a pgadmin instance can be started:

npm run pgadmin (Default port 15432)

All ports are mapped to the host running the script. Running the setupdb script also creates a ./postgres-data directory that is mounted on the setupdb docker container, in order to enable data persistence for tables, etc.

Pgadmin config files are already set at the ./pgadmin subdirectory (server.json and pgpass). Additional configuration such as environment variables are present at ./.env.db

2021-10-12 08:11 UTC, claudenirmf requested changes
Just went through the file changes. I'll be running the project on my machine now.

2021-10-12 08:11 UTC, claudenirmf commented on .gitignore
> +.postgres-data
Why can you ignore the postgres volume, but not the pgadmin one?

2021-10-12 08:11 UTC, claudenirmf commented on pgadmin/pgpass
> +pgdb:5432:test_db:root:root
What does this file do?

2021-10-12 08:11 UTC, claudenirmf commented on pgadmin/servers.json
> +{
What does this file do?

2021-10-12 08:11 UTC, claudenirmf commented on package.json
> +    "setupdb": "docker-compose -f docker-compose_setupdb.yml up -d",
Do not run it detached. I want it in the foreground to easily interact with the process through the terminal and to terminate it with a `ctrl+C`.

2021-10-12 08:11 UTC, claudenirmf commented on package.json
> +    "pgadmin": "docker-compose -f docker-compose_pgadmin.yml up -d"
Do not run it detached. I want it in the foreground to easily interact with the process through the terminal and to terminate it with a `ctrl+C`.

2021-10-12 08:11 UTC, claudenirmf commented on .env.db
> +DB_EXT_PORT=5432
Why did you create a new `.env` file? Is it really necessary? Or can you use `.env.example`?

2021-10-12 08:11 UTC, claudenirmf commented on docker-compose_pgadmin.yml
> +      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_LOGIN}"
How does `docker-compose` knows where to find these environment variables? Do you need a default `.env` file? Did it get the values from `.env.db`?

2021-10-12 08:11 UTC, claudenirmf commented on pgadmin/pgpass
> +pgdb:5432:test_db:root:root
Can you have this on the `.env` and provide the value to `pgAdmin` through the `docker-compose._pgadmin.yml` file?

2021-10-12 08:11 UTC, claudenirmf commented on pgadmin/servers.json
> +{
Can you have this on the `.env` and provide the value to `pgAdmin` through the `docker-compose._pgadmin.yml` file?

2021-10-12 08:14 UTC, claudenirmf commented on package.json
> +    "setupdb": "docker-compose -f docker-compose_setupdb.yml up -d",
Also, change the `setupdb` name to just `db`. "Setup" is a bad name here because that is not what you are doing. You are running the db, not setting it up.

2021-10-12 08:18 UTC, claudenirmf commented on package.json
> +    "setupdb": "docker-compose -f docker-compose_setupdb.yml up -d",
Also, change the name of the file name from `docker-compose_setupdb.yml` to `docker-compose_postgres.yml`, referring to the name of the application, not one of its steps.

2021-10-12 08:24 UTC, claudenirmf commented on pgadmin/pgpass
> +pgdb:5432:test_db:root:root
By the way, if we cannot have this on an environment file, it will quite annoying changing the postgres port (default `5432`) because we'll have to change multiple files (going through that right now myself).

2021-10-12 08:24 UTC, claudenirmf commented on pgadmin/servers.json
> +            "Port": 5432,
By the way, if we cannot have this on an environment file, it will quite annoying changing the postgres port (default `5432`) because we'll have to change multiple files (going through that right now myself). The same applies to other variables,

2021-10-12 08:38 UTC, claudenirmf commented
For the instructions: on Mac, it is necessary to the Docker engine before using `docker-compose` or `docker`, otherwise you'll get `"Connection refused"` errors. I believe Windows would require something similar because Docker is native to Linux.

2021-10-12 08:43 UTC, claudenirmf commented
The development account `test@test.com` (password `test`) account does not login in as root automatically on `pgAdmin`. Even more weird, is that you need to enter a different password (`root`) to actually login. Try to make the development account login as root from the start, or at least have a single password for everything.

2021-10-12 23:09 UTC, jcargoncalves commented on .env.db
> +DB_EXT_PORT=5432
In fact, it was just me being extra careful with the repository files. I didn't know if the main application would always run with the db included, as there are two env files (.env.example and .env.test). If this is the default scenario, I can easily copy my environment variables to .env.example.

2021-10-12 23:12 UTC, jcargoncalves commented on .gitignore
> +.postgres-data
The pgadmin directory had the servers.json needed for pgadmin to run with the correct db configuration "out of the box". I have simplified in my new version of the code, removing the directory and generating the json files dynamically from the environment variables. I will comment in details on my new commits

2021-10-12 23:13 UTC, joaogoncalves777 commented on docker-compose_pgadmin.yml
> +      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_LOGIN}"
It gets the variables from .env. The other .env files are just templates to be renamed and copied as .env, in order to run the application.

2021-10-12 23:14 UTC, joaogoncalves777 commented on pgadmin/pgpass
> +pgdb:5432:test_db:root:root
I've removed the need of this file. I will address this issue on my new commits.

2021-10-12 23:15 UTC, joaogoncalves777 commented on pgadmin/servers.json
> +{
The servers.json file is necessary for the docker image we are using for pgadmin (dpage/pgadmin4). It is used to load the postgresql db configuration (hostname, port,etc) automatically when the docker container is loaded.

2021-10-12 23:54 UTC, jcargoncalves commented
I have changed the code in order to make the setup of postgresql DB and pgadmin more flexible and using solely the environment variables. 

Also, I have created a simple script "pgadmin-setup.js" to generate the pgadmin-servers.json file. This file is needed to start the docker pgadmin container already configured with the db specifications (hostname, port, user,etc....). The only thing that I was not able to automate was the login at the pgadmin webpage and the db password.

Please let me know if the changes are sufficient for the requested code reviews. I have tested and they seem to work well. Even tested creating a table and inserting some values on it and the data is persistent, even after stopping and pruning the docker containers.

2021-10-13 00:01 UTC, joaogoncalves777 commented
Two small issues I have found on Linux (Specifically Ubuntu 20.04):

- The pgadmin web interface takes a while to start (Same as reported by claudenirmf on Mac).
- The postgres-data directory's owner is changed to "systemd-coredump" after the docker postgres container mounts the directory on its filesystem.

The first problem seems to be either an issue with the docker image or with pgadmin4 itself. The second is a bug with ubuntu and docker, but none of them interferes with the usage of the db or the web interface.

2021-10-19 09:29 UTC, claudenirmf commented
> Two small issues I have found on Linux (Specifically Ubuntu 20.04):
> 
> * The pgadmin web interface takes a while to start.

My guess is that the image is taking some time to load on your machine. How much time are we talking about? Do you have Ubuntu on a VM or directly installed into your disk?

> * The postgres-data directory's owner is changed to "systemd-coredump" after the docker postgres container mounts the directory on its filesystem.

Do we need to add something to the `.gitignore` file?

2021-10-19 15:07 UTC, claudenirmf approved these changes

2021-10-19 15:08 UTC, merged